version: '3.8'

services:
  xmtp-agent:
    build: .
    image: ${DOCKER_REGISTRY}/xmtp-shade-agent:${VERSION:-latest}
    environment:
      - NODE_ENV=production
      - AGENT_PRIVATE_KEY=${AGENT_PRIVATE_KEY}
      - XMTP_ENV=${XMTP_ENV:-production}
      - BASE_RPC_URL=${BASE_RPC_URL}
      - BASE_API_KEY=${BASE_API_KEY}
      - MPC_PUBLIC_KEY_MAINNET=${MPC_PUBLIC_KEY_MAINNET}
      - MPC_PUBLIC_KEY_TESTNET=${MPC_PUBLIC_KEY_TESTNET}
      - NEXT_PUBLIC_contractId=${NEXT_PUBLIC_contractId}
    volumes:
      - xmtp-data:/app/xmtp-db
      - ./logs:/app/logs
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: unless-stopped
    platform: linux/amd64 # Explicitly set for TDX
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  xmtp-data:
